### ISSUE TITLE
我在测试你的代码的时候遇到了问题，params.String() 无法正确返回值

### ISSUE THREAD

**Issue by tanzhilangnw** [CcoWzh/BBS04#1]
我配置好PBC库之后，运行你的代码发现出现错误，设断点调试发现，params.String()返回值为nil，想请教一下你哪里出了问题。 

![image](https://github.com/CcoWzh/BBS04/assets/80900663/7a80abe7-e026-4428-b55a-32fac76dcf05)

**Comment by CcoWzh** [comment]
对不起，很久没梳理这段代码了，我也不知道哪里出问题了。我猜测应该是没有安装pbc库，或者是其他依赖有问题



在 2023-10-18 15:15:57，"xp" ***@***.***> 写道：

我配置好PBC库之后，运行你的代码发现出现错误，设断点调试发现，params.String()返回值为nil，想请教一下你哪里出了问题。

**Comment by tanzhilangnw** [comment]
谢谢你的回答，之前在windows下运行的代码，我把代码放在ubnutu22.04上运行一切正常
